networks:
  microMemorandum:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=ROOT
     - MYSQL_DATABASE=micro_todolist
     - MYSQL_USER=micro_memorandum
     - MYSQL_PASSWORD=micro_memorandum
     - TZ=Asia/Shanghai
    ports:
     - "3306:3306"
    volumes:
     - ./data/mysql:/var/lib/mysql
    networks:
     - microMemorandum

  etcd:
    container_name: etcd
    image: "quay.io/coreos/etcd:v3.5.5"
    restart: on-failure
    privileged: true
    ports:
     - "2379:2379"
    environment:
     - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
     - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
     - ALLOW_NONE_AUTHENTICATION=yes
     - ETCD_API=3
     - ETCD_CERT_FILE="/path/to/server.crt"
     - ETCD_KEY_FILE="/path/to/server.key"
     - ETCD_AUTH="simple"
     - ETCD_AUTH_USER="micro_memorandum"
     - ETCD_AUTH_PASSWORD="micro_memorandum"
    networks:
     - microMemorandum
  
  rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq
   ports:
    - "5672:5672" # AMQP端口
    - "15672:15672" # 管理界面端口
   environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
   networks:
    - microMemorandum

