// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: taskService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id" form:"id"
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id"`
	// @inject_tag: json:"uid" form:"uid"
	Uid uint64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid" form:"uid"`
	// @inject_tag: json:"title" form:"title"
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title" form:"title"`
	// @inject_tag: json:"content" form:"content"
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content" form:"content"`
	// @inject_tag: json:"start_time" form:"start_time"
	StartTime int64 `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time" form:"start_time"`
	// @inject_tag: json:"end_time" form:"end_time"
	EndTime int64 `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time" form:"end_time"`
	// @inject_tag: json:"status" form:"status"
	Status int64 `protobuf:"varint,7,opt,name=status,proto3" json:"status" form:"status"`
	// @inject_tag: json:"create_time" form:"create_time"
	CreateTime int64 `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time" form:"create_time"`
	// @inject_tag: json:"update_time" form:"update_time"
	UpdateTime    int64 `protobuf:"varint,9,opt,name=update_time,json=updateTime,proto3" json:"update_time" form:"update_time"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskModel) Reset() {
	*x = TaskModel{}
	mi := &file_taskService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskModel) ProtoMessage() {}

func (x *TaskModel) ProtoReflect() protoreflect.Message {
	mi := &file_taskService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskModel.ProtoReflect.Descriptor instead.
func (*TaskModel) Descriptor() ([]byte, []int) {
	return file_taskService_proto_rawDescGZIP(), []int{0}
}

func (x *TaskModel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskModel) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TaskModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskModel) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskModel) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskModel) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TaskModel) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TaskModel) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *TaskModel) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type TaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id" form:"id"
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id"`
	// @inject_tag: json:"uid" form:"uid"
	Uid uint64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid" form:"uid"`
	// @inject_tag: json:"title" form:"title"
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title" form:"title"`
	// @inject_tag: json:"content" form:"content"
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content" form:"content"`
	// @inject_tag: json:"start_time" form:"start_time"
	StartTime int64 `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time" form:"start_time"`
	// @inject_tag: json:"end_time" form:"end_time"
	EndTime int64 `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time" form:"end_time"`
	// @inject_tag: json:"status" form:"status"
	Status int64 `protobuf:"varint,7,opt,name=status,proto3" json:"status" form:"status"`
	// @inject_tag: json:"start" form:"start"
	Start uint32 `protobuf:"varint,8,opt,name=start,proto3" json:"start" form:"start"`
	// @inject_tag: json:"limit" form:"limit"
	Limit         uint32 `protobuf:"varint,9,opt,name=limit,proto3" json:"limit" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_taskService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_taskService_proto_rawDescGZIP(), []int{1}
}

func (x *TaskRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TaskRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TaskRequest) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TaskRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TaskListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"task_list"
	TaskList []*TaskModel `protobuf:"bytes,1,rep,name=task_list,json=taskList,proto3" json:"task_list"`
	// @inject_tag: json:"count"
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
	// @inject_tag: json:"code"
	Code          uint32 `protobuf:"varint,3,opt,name=code,proto3" json:"code"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskListResponse) Reset() {
	*x = TaskListResponse{}
	mi := &file_taskService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListResponse) ProtoMessage() {}

func (x *TaskListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListResponse.ProtoReflect.Descriptor instead.
func (*TaskListResponse) Descriptor() ([]byte, []int) {
	return file_taskService_proto_rawDescGZIP(), []int{2}
}

func (x *TaskListResponse) GetTaskList() []*TaskModel {
	if x != nil {
		return x.TaskList
	}
	return nil
}

func (x *TaskListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TaskListResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type TaskDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"task_detail"
	TaskDetail *TaskModel `protobuf:"bytes,1,opt,name=task_detail,json=taskDetail,proto3" json:"task_detail"`
	// @inject_tag: json:"code"
	Code          uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDetailResponse) Reset() {
	*x = TaskDetailResponse{}
	mi := &file_taskService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetailResponse) ProtoMessage() {}

func (x *TaskDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetailResponse.ProtoReflect.Descriptor instead.
func (*TaskDetailResponse) Descriptor() ([]byte, []int) {
	return file_taskService_proto_rawDescGZIP(), []int{3}
}

func (x *TaskDetailResponse) GetTaskDetail() *TaskModel {
	if x != nil {
		return x.TaskDetail
	}
	return nil
}

func (x *TaskDetailResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_taskService_proto protoreflect.FileDescriptor

const file_taskService_proto_rawDesc = "" +
	"\n" +
	"\x11taskService.proto\x12\x02pb\"\xf1\x01\n" +
	"\tTaskModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\t \x01(\x03R\n" +
	"updateTime\"\xdd\x01\n" +
	"\vTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12\x14\n" +
	"\x05start\x18\b \x01(\rR\x05start\x12\x14\n" +
	"\x05limit\x18\t \x01(\rR\x05limit\"h\n" +
	"\x10TaskListResponse\x12*\n" +
	"\ttask_list\x18\x01 \x03(\v2\r.pb.TaskModelR\btaskList\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x12\n" +
	"\x04code\x18\x03 \x01(\rR\x04code\"X\n" +
	"\x12TaskDetailResponse\x12.\n" +
	"\vtask_detail\x18\x01 \x01(\v2\r.pb.TaskModelR\n" +
	"taskDetail\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code2\x9d\x02\n" +
	"\vTaskService\x125\n" +
	"\n" +
	"CreateTask\x12\x0f.pb.TaskRequest\x1a\x16.pb.TaskDetailResponse\x125\n" +
	"\fGetTasksList\x12\x0f.pb.TaskRequest\x1a\x14.pb.TaskListResponse\x122\n" +
	"\aGetTask\x12\x0f.pb.TaskRequest\x1a\x16.pb.TaskDetailResponse\x125\n" +
	"\n" +
	"UpdateTask\x12\x0f.pb.TaskRequest\x1a\x16.pb.TaskDetailResponse\x125\n" +
	"\n" +
	"DeleteTask\x12\x0f.pb.TaskRequest\x1a\x16.pb.TaskDetailResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_taskService_proto_rawDescOnce sync.Once
	file_taskService_proto_rawDescData []byte
)

func file_taskService_proto_rawDescGZIP() []byte {
	file_taskService_proto_rawDescOnce.Do(func() {
		file_taskService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskService_proto_rawDesc), len(file_taskService_proto_rawDesc)))
	})
	return file_taskService_proto_rawDescData
}

var file_taskService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_taskService_proto_goTypes = []any{
	(*TaskModel)(nil),          // 0: pb.TaskModel
	(*TaskRequest)(nil),        // 1: pb.TaskRequest
	(*TaskListResponse)(nil),   // 2: pb.TaskListResponse
	(*TaskDetailResponse)(nil), // 3: pb.TaskDetailResponse
}
var file_taskService_proto_depIdxs = []int32{
	0, // 0: pb.TaskListResponse.task_list:type_name -> pb.TaskModel
	0, // 1: pb.TaskDetailResponse.task_detail:type_name -> pb.TaskModel
	1, // 2: pb.TaskService.CreateTask:input_type -> pb.TaskRequest
	1, // 3: pb.TaskService.GetTasksList:input_type -> pb.TaskRequest
	1, // 4: pb.TaskService.GetTask:input_type -> pb.TaskRequest
	1, // 5: pb.TaskService.UpdateTask:input_type -> pb.TaskRequest
	1, // 6: pb.TaskService.DeleteTask:input_type -> pb.TaskRequest
	3, // 7: pb.TaskService.CreateTask:output_type -> pb.TaskDetailResponse
	2, // 8: pb.TaskService.GetTasksList:output_type -> pb.TaskListResponse
	3, // 9: pb.TaskService.GetTask:output_type -> pb.TaskDetailResponse
	3, // 10: pb.TaskService.UpdateTask:output_type -> pb.TaskDetailResponse
	3, // 11: pb.TaskService.DeleteTask:output_type -> pb.TaskDetailResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_taskService_proto_init() }
func file_taskService_proto_init() {
	if File_taskService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskService_proto_rawDesc), len(file_taskService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskService_proto_goTypes,
		DependencyIndexes: file_taskService_proto_depIdxs,
		MessageInfos:      file_taskService_proto_msgTypes,
	}.Build()
	File_taskService_proto = out.File
	file_taskService_proto_goTypes = nil
	file_taskService_proto_depIdxs = nil
}
